import { create } from "zustand";
import { Employee } from "./types/employee";

type EmployeeFilters = {
  departments: string[];
  positions: string[];
  minExperience?: number;
  maxExperience?: number;
};

type EmployeeStore = {
  employees: Employee[];
  departments: string[];
  positions: string[];
  filters: EmployeeFilters;
  setFilters: (filters: Partial<EmployeeFilters>) => void;
};

export const useEmployeeStore = create<EmployeeStore>((set) => ({
  employees: [
    {
      id: "1",
      name: "Иванов Иван",
      position: "CEO",
      department: "Исполнительное руководство",
      experience: 15,
      rating: 98,
      email: "ivanov@company.com",
    },
    {
      id: "2",
      name: "Петрова Мария",
      position: "CTO",
      department: "Технический отдел",
      experience: 12,
      rating: 95,
      managerId: "1",
      email: "petrova@company.com",
    },
    {
      id: "3",
      name: "Сидоров Алексей",
      position: "CFO",
      department: "Финансы",
      experience: 14,
      rating: 92,
      managerId: "1",
      email: "sidorov@company.com",
    },
    {
      id: "4",
      name: "Козлова Анна",
      position: "HR Director",
      department: "HR",
      experience: 10,
      rating: 90,
      managerId: "1",
      email: "kozlova@company.com",
    },
    // Технический отдел
    {
      id: "5",
      name: "Григорьев Павел",
      position: "Head of Development",
      department: "Разработка",
      experience: 8,
      rating: 92,
      managerId: "2",
      email: "grigoriev@company.com",
    },
    {
      id: "6",
      name: "Семенова Ольга",
      position: "Head of QA",
      department: "Тестирование",
      experience: 7,
      rating: 48,
      managerId: "2",
      email: "semenova@company.com",
    },
    {
      id: "7",
      name: "Васильев Дмитрий",
      position: "DevOps Lead",
      department: "DevOps",
      experience: 9,
      rating: 91,
      managerId: "2",
      email: "vasilev@company.com",
    },
    // Команда разработки
    {
      id: "8",
      name: "Николаев Артем",
      position: "Team Lead",
      department: "Backend",
      experience: 6,
      rating: 59,
      managerId: "5",
      email: "nikolaev@company.com",
    },
    {
      id: "9",
      name: "Морозова Екатерина",
      position: "Senior Developer",
      department: "Backend",
      experience: 5,
      rating: 87,
      managerId: "8",
      email: "morozova@company.com",
    },
    {
      id: "10",
      name: "Белов Максим",
      position: "Middle Developer",
      department: "Frontend",
      experience: 3,
      rating: 22,
      managerId: "8",
      email: "belov@company.com",
    },
    {
      id: "11",
      name: "Тихонова Алина",
      position: "Junior Developer",
      department: "Mobile",
      experience: 1,
      rating: 75,
      managerId: "8",
      email: "tihonova@company.com",
    },
    // Команда тестирования
    {
      id: "12",
      name: "Федоров Игорь",
      position: "QA Lead",
      department: "QA",
      experience: 4,
      rating: 35,
      managerId: "6",
      email: "fedorov@company.com",
    },
    {
      id: "13",
      name: "Дмитриева Вероника",
      position: "Senior QA",
      department: "Automation",
      experience: 3,
      rating: 83,
      managerId: "12",
      email: "dmitrieva@company.com",
    },
    // DevOps команда
    {
      id: "14",
      name: "Крылов Станислав",
      position: "DevOps Engineer",
      department: "Infrastructure",
      experience: 4,
      rating: 86,
      managerId: "7",
      email: "krylov@company.com",
    },
    // HR Department
    {
      id: "15",
      name: "Мельникова Дарья",
      position: "HR Manager",
      department: "Recruitment",
      experience: 4,
      rating: 84,
      managerId: "4",
      email: "melnikova@company.com",
    },
    {
      id: "16",
      name: "Соколов Андрей",
      position: "HR Specialist",
      department: "Employee Relations",
      experience: 2,
      rating: 78,
      managerId: "4",
      email: "sokolov@company.com",
    },
  ],
  // employees: [
  //   {
  //     id: "1",
  //     name: "Иванов Иван",
  //     position: "CEO",
  //     department: "Управление",
  //     experience: 10,
  //     rating: 95,
  //   },
  //   {
  //     id: "2",
  //     name: "Петрова Мария",
  //     position: "CTO",
  //     department: "IT",
  //     experience: 8,
  //     rating: 90,
  //     managerId: "1",
  //   },
  //   {
  //     id: "3",
  //     name: "Смирнов Сергей",
  //     position: "Дизайнер",
  //     department: "Дизайн",
  //     experience: 3,
  //     rating: 85,
  //     managerId: "2",
  //   },
  //   {
  //     id: "4",
  //     name: "Кузнецов Александр",
  //     position: "Менеджер",
  //     department: "HR",
  //     experience: 5,
  //     rating: 80,
  //     managerId: "1",
  //   },
  //   {
  //     id: "5",
  //     name: "Белый Дмитрий",
  //     position: "Разработчик",
  //     department: "Отдел разработки",
  //     experience: 2,
  //     rating: 75,
  //     managerId: "2",
  //   },
  //   {
  //     id: "6",
  //     name: "Галкин Андрей",
  //     position: "Разработчик",
  //     department: "Отдел разработки",
  //     experience: 1,
  //     rating: 70,
  //     managerId: "2",
  //   },
  //   {
  //     id: "7",
  //     name: "Смирнов Владимир",
  //     position: "Разработчик",
  //     department: "Отдел разработки",
  //     experience: 1,
  //     rating: 65,
  //     managerId: "4",
  //   },
  //   {
  //     id: "8",
  //     name: "Кузнецов Дмитрий",
  //     position: "Разработчик",
  //     department: "Отдел разработки",
  //     experience: 1,
  //     rating: 60,
  //     managerId: "2",
  //   },
  //   {
  //     id: "9",
  //     name: "Серебряков Александр",
  //     position: "Разработчик",
  //     department: "Отдел разработки",
  //     experience: 1,
  //     rating: 55,
  //     managerId: "2",
  //   },
  //   {
  //     id: "10",
  //     name: "Борисов Алексей",
  //     position: "Разработчик",
  //     department: "Отдел разработки",
  //     experience: 1,
  //     rating: 50,
  //     managerId: "4",
  //   },
  //   {
  //     id: "11",
  //     name: "Петров Александр",
  //     position: "Разработчик",
  //     department: "Отдел разработки",
  //     experience: 1,
  //     rating: 45,
  //     managerId: "2",
  //   },
  // ],
  departments: ["Отдел разработки", "Отдел маркетинга", "HR"],
  positions: ["Разработчик", "Менеджер", "Дизайнер"],
  filters: {
    departments: [],
    positions: [],
  },
  setFilters: (newFilters) =>
    set((state) => ({
      filters: { ...state.filters, ...newFilters },
    })),
}));
